<h1 style="color: #F7DC6F; border-bottom: 3px solid #F0B27A; padding-bottom: 8px;">
🤖 AI & ML Course with BinX — Week 3 — Day 2 — Linear Regression
</h1>

<div style="background-color: #1a1a2e; border-left: 5px solid #F0B27A; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
<h2 style="color: #F7DC6F; font-family: 'Trebuchet MS', sans-serif; font-size: 22px; margin: 0 0 10px 0;">
📈 2.1 What Linear Regression Does
</h2>
<p style="color: #FAD7A0; font-family: 'Trebuchet MS', sans-serif; font-size: 15px; line-height: 1.8;">
Linear regression predicts a <strong style="color: #F7DC6F;">continuous number</strong> by fitting the best straight line (or hyperplane) through the data. Its prediction is exactly the dot product from Week 2:
</p>
<p style="color: #F7DC6F; font-family: 'Trebuchet MS', sans-serif; font-size: 16px; font-weight: bold; text-align: center; margin: 12px 0;">
prediction = (feature₁ × weight₁) + (feature₂ × weight₂) + ... + bias
</p>
<p style="color: #FAD7A0; font-family: 'Trebuchet MS', sans-serif; font-size: 15px; line-height: 1.8;">
Training means finding the weights that make the line fit the data as closely as possible.
</p>
</div>

<div style="background-color: #1a1a2e; border-left: 5px solid #F0B27A; padding: 15px; border-radius: 8px; margin-bottom: 10px;">

<h2 style="color: #F7DC6F; font-family: 'Trebuchet MS', sans-serif; font-size: 22px; margin: 0 0 10px 0;">
🤖 2.2 Training and Predicting
</h2>

<p style="color: #FAD7A0; font-family: 'Trebuchet MS', sans-serif; font-size: 15px; line-height: 1.8;">
We use <strong style="color: #F7DC6F;">Scikit-learn</strong> to train a linear regression model in 3 simple steps:
</p>

<ol style="color: #FAD7A0; font-family: 'Trebuchet MS', sans-serif; font-size: 15px; line-height: 2;">
<li>Import the model</li>
<li>Fit it on training data</li>
<li>Use it to predict on new data</li>
</ol>

</div>

In [19]:
print(df.dtypes)

gender                     str
age                    float64
hypertension             int64
heart_disease            int64
smoking_history            str
bmi                    float64
HbA1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object


In [1]:
import pandas as pd
df = pd.read_csv("diabetes.csv")

In [2]:
df = pd.get_dummies(df, columns=["gender", "smoking_history"], drop_first=True)

In [3]:
X = df.drop("diabetes", axis=1)
y = df["diabetes"]

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](13,)","[0. ,0.09,0.12,...,0.03,0.01,0.02]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](13,)","['age','hypertension','heart_disease',...,'smoking_history_former', 'smoking_history_never','smoking_history_not current']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,-0.8716
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,13
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(13)


<div style="background-color: #1a1a2e; border-left: 5px solid #F0B27A; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
<h2 style="color: #F7DC6F; font-family: 'Trebuchet MS', sans-serif; font-size: 22px; margin: 0 0 10px 0;">
🔍 2.3 Interpreting Coefficients
</h2>
<p style="color: #FAD7A0; font-family: 'Trebuchet MS', sans-serif; font-size: 15px; line-height: 1.8;">
After fitting, each feature has a <strong style="color: #F7DC6F;">coefficient</strong> (its weight) and the model has one <strong style="color: #F7DC6F;">intercept</strong> (the bias).
A coefficient tells you how much the prediction changes when that feature increases by one unit, holding others constant — this interpretability is a major reason linear regression remains widely used even in the deep-learning era.
</p>
</div>

In [6]:
print(model.coef_)       
print(model.intercept_)  

[ 0.00133803  0.09244247  0.11817645  0.00405525  0.08144681  0.00227524
  0.01268014 -0.04683423  0.01052365  0.00798245  0.02715048  0.00978844
  0.01634411]
-0.8715818209053153


<div style="background-color: #1a1a2e; border-left: 5px solid #F0B27A; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
<h2 style="color: #F7DC6F; font-family: 'Trebuchet MS', sans-serif; font-size: 22px; margin: 0 0 10px 0;">
📊 2.4 Regression Metrics
</h2>
<p style="color: #FAD7A0; font-family: 'Trebuchet MS', sans-serif; font-size: 15px; line-height: 1.8;">
A regression model's error is measured by how far its predictions land from the true values. The three standard metrics:
</p>
<table style="width: 100%; border-collapse: collapse; margin: 12px 0; font-family: 'Trebuchet MS', sans-serif;">
<tr style="background-color: #F0B27A;">
<th style="padding: 8px; color: #1a1a2e; text-align: left;">Metric</th>
<th style="padding: 8px; color: #1a1a2e; text-align: left;">Meaning</th>
<th style="padding: 8px; color: #1a1a2e; text-align: left;">Interpretation</th>
</tr>
<tr>
<td style="padding: 8px; color: #FAD7A0; border-bottom: 1px solid #F0B27A;">MAE</td>
<td style="padding: 8px; color: #FAD7A0; border-bottom: 1px solid #F0B27A;">Mean Absolute Error</td>
<td style="padding: 8px; color: #FAD7A0; border-bottom: 1px solid #F0B27A;">Average size of the error, in the target's units — easy to explain</td>
</tr>
<tr>
<td style="padding: 8px; color: #FAD7A0; border-bottom: 1px solid #F0B27A;">RMSE</td>
<td style="padding: 8px; color: #FAD7A0; border-bottom: 1px solid #F0B27A;">Root Mean Squared Error</td>
<td style="padding: 8px; color: #FAD7A0; border-bottom: 1px solid #F0B27A;">Like MAE but penalizes large errors more heavily</td>
</tr>
<tr>
<td style="padding: 8px; color: #FAD7A0;">R²</td>
<td style="padding: 8px; color: #FAD7A0;">Coefficient of determination</td>
<td style="padding: 8px; color: #FAD7A0;">Fraction of variance explained; 1.0 is perfect, 0 is no better than the mean</td>
</tr>
</table>
</div>

In [8]:
predictions = model.predict(X_test)

In [9]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print(mean_absolute_error(y_test, predictions))
print(np.sqrt(mean_squared_error(y_test, predictions)))  # RMSE
print(r2_score(y_test, predictions))

0.15456408961609758
0.22622813454318516
0.3447543280602635


<div style="background-color: #1a1a2e; border-left: 5px solid #F0B27A; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
<p style="color: #FAD7A0; font-family: 'Trebuchet MS', sans-serif; font-size: 15px; line-height: 1.8;">
Always compare a model's metric against a simple <strong style="color: #F7DC6F;">baseline</strong> (e.g. predicting the mean for every row). A model that cannot beat the baseline has learned nothing useful.
</p>
</div>

<div style="background-color: #1a1a2e; border-left: 5px solid #F0B27A; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
<h2 style="color: #F7DC6F; font-family: 'Trebuchet MS', sans-serif; font-size: 22px; margin: 0 0 10px 0;">
🧪 Hands-On Lab: Predicting a Continuous Value
</h2>
<p style="color: #FAD7A0; font-family: 'Trebuchet MS', sans-serif; font-size: 15px; line-height: 1.8;">
Applying everything from this lesson on a real regression dataset.
</p>
</div>

<div style="background-color: #1a1a2e; border-left: 5px solid #F0B27A; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
<h3 style="color: #F7DC6F; font-family: 'Trebuchet MS', sans-serif; font-size: 18px; margin: 0;">
Step 1: Train LinearRegression on a Regression Dataset
</h3>
</div>

In [12]:
model = LinearRegression()
model.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](13,)","[0. ,0.09,0.12,...,0.03,0.01,0.02]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](13,)","['age','hypertension','heart_disease',...,'smoking_history_former', 'smoking_history_never','smoking_history_not current']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,-0.8716
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,13
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(13)


<div style="background-color: #1a1a2e; border-left: 5px solid #F0B27A; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
<h3 style="color: #F7DC6F; font-family: 'Trebuchet MS', sans-serif; font-size: 18px; margin: 0;">
Step 2: Report Coefficients and Identify Strongest Feature
</h3>
</div>

In [13]:
import pandas as pd

coef_df = pd.DataFrame({
    "feature": X.columns,
    "coefficient": model.coef_
}).sort_values(by="coefficient", key=abs, ascending=False)

print(coef_df)

                        feature  coefficient
2                 heart_disease     0.118176
1                  hypertension     0.092442
4                   HbA1c_level     0.081447
7                  gender_Other    -0.046834
10       smoking_history_former     0.027150
12  smoking_history_not current     0.016344
6                   gender_Male     0.012680
8       smoking_history_current     0.010524
11        smoking_history_never     0.009788
9          smoking_history_ever     0.007982
3                           bmi     0.004055
5           blood_glucose_level     0.002275
0                           age     0.001338


<div style="background-color: #1a1a2e; border-left: 5px solid #F0B27A; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
<h3 style="color: #F7DC6F; font-family: 'Trebuchet MS', sans-serif; font-size: 18px; margin: 0;">
Step 3: Evaluate Model with MAE, RMSE, and R²
</h3>
</div>

In [14]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print(mean_absolute_error(y_test, predictions))
print(np.sqrt(mean_squared_error(y_test, predictions)))  # RMSE
print(r2_score(y_test, predictions))

0.15456408961609758
0.22622813454318516
0.3447543280602635


<div style="background-color: #1a1a2e; border-left: 5px solid #F0B27A; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
<h3 style="color: #F7DC6F; font-family: 'Trebuchet MS', sans-serif; font-size: 18px; margin: 0;">
Step 4: Compare RMSE Against Baseline
</h3>
</div>

In [15]:
baseline_prediction = np.full_like(y_test, y_train.mean(), dtype=float)
baseline_rmse = np.sqrt(mean_squared_error(y_test, baseline_prediction))

model_rmse = np.sqrt(mean_squared_error(y_test, predictions))

print(f"Baseline RMSE: {baseline_rmse:.4f}")
print(f"Model RMSE: {model_rmse:.4f}")

if model_rmse < baseline_rmse:
    print("✅ The model adds value over the baseline.")
else:
    print("⚠️ The model does NOT beat the baseline.")

Baseline RMSE: 0.2795
Model RMSE: 0.2262
✅ The model adds value over the baseline.


<div style="background-color: #1a1a2e; border-left: 5px solid #F0B27A; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
<h3 style="color: #F7DC6F; font-family: 'Trebuchet MS', sans-serif; font-size: 18px; margin: 0;">
Step 5: Document Interpretation of Results
</h3>
</div>

<div style="background-color: #1a1a2e; border-left: 5px solid #F0B27A; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
<p style="color: #FAD7A0; font-family: 'Trebuchet MS', sans-serif; font-size: 15px; line-height: 1.8;">
The model's RMSE (<strong style="color: #F7DC6F;">0.2262</strong>) is lower than the baseline RMSE (<strong style="color: #F7DC6F;">0.2795</strong>), meaning its predictions are, on average, closer to the true values than simply guessing the mean every time.
</p>

<p style="color: #FAD7A0; font-family: 'Trebuchet MS', sans-serif; font-size: 15px; line-height: 1.8;">
This confirms the model <strong style="color: #F7DC6F;">has learned a useful pattern</strong> from the data rather than just memorizing the average outcome. The feature with the strongest effect was <strong style="color: #F7DC6F;">heart_disease</strong>, with a coefficient of <strong style="color: #F7DC6F;">0.1182</strong>, indicating that it had the greatest influence on the model's predictions among all input features.
</p>
</div>